### ISSUE TITLE
https://fatcherjs.github.io/v1.docs/    链接QuickStart是404

### ISSUE THREAD

**Issue by yilihjy** [fatcherjs/v1.docs#2]
链接404了
We will learn how to send a fatcher request in next chapter [QuickStart](https://fatcherjs.github.io/quick-start)

**Comment by yilihjy** [comment]
https://github.com/fatcherjs/v1.docs/blame/master/src/pages/index.mdx#L41

**Comment by fanhaoyuan** [comment]
👍
